versity/versitygw

- s3api/middlewares/authentication.go
> V4 payload header support

- auth/iam_internal.go
- cmd/versitygw/admin.go
- integration/tests.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/router.go
Some cleanup in admin cli commands and api.
bug fix in IAM delete user account.
Changed admin apis methods, not to be conflicting with main apis
> Admin api routing

- backend/posix/posix.go
…r when the object doesn't exist
> Fix Posix Delete Objects

- backend/posix/posix.go
- integration/action-tests.go
- integration/tests.go
- integration/utils.go
- s3api/controllers/base.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
Bug fixing for ListMultipartUploads action
> Issue-207, 198

- auth/iam.go
- auth/iam_internal.go
- cmd/versitygw/admin.go
- integration/utils.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/iam_moq_test.go
- s3api/router.go
1. Added admin CLI action to list the users as json in the terminal
2. Added admin api endpoint to list the users.
3. Added unit tests for the api endpoint.
> Issue 205 list users in admin CLI

- auth/acl.go
- backend/backend.go
- backend/posix/posix.go
- cmd/versitygw/admin.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/backend_moq_test.go
- s3api/router.go
1. Added an admin api endpoint to change a bucket owner
2. Added a CLI action to update an existing bucket owner
> Issue 206, Change bucket owner admin API and CLI action

- s3api/controllers/base_test.go
1. Fixed vet warnings, removed fiber.Ctx copying
> Issue 206, vet warnings

- integration/action-tests.go
- integration/tests.go
1. An integration test case to create a bucket as a user
> CreateBucket integration test

- auth/acl.go
- backend/posix/posix.go
- s3api/router.go
1. Removed some unnecessary logs from posix and acl
2. Added missing comments for router
> App cleanup(minor changes)

- backend/backend.go
- backend/posix/posix.go
- cmd/versitygw/admin.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/backend_moq_test.go
- s3api/router.go
- s3response/s3response.go
1. Added an admin API to list all the buckets and its owners.
2. Added an admin CLI action to list the buckets and owners.
3. Added unit test cases for the admin API.
> Issue 217, Admin API and CLI action to list all the buckets and its owners.

- cmd/versitygw/main.go
- s3api/admin-router.go
- s3api/admin-server.go
- s3api/router.go
1. Added CLI flags to run admin server as a different server
2. It could be run within the same network by not specifying any admin related flags
> Issue 232, An option to run admin server as a separate one.

- backend/posix/posix.go
- integration/action-tests.go
- integration/tests.go
Added the error case for CopyObject action to copy the object into itself
> Issue 243 CopyObject error case to copy the object into itself

- auth/acl.go
- backend/posix/posix.go
- s3api/controllers/base.go
Removed unused `bucket` argument from VerifyACL function.
> VerifyACL function cleanup

- integration/action-tests.go
- integration/tests.go
- integration/utils.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
1. Changed DeleteObjectTagging successful response status code from 200 to 204.(identical to AWS)
> Issue 247, DeleteObjectTagging successful response status

- backend/backend.go
- backend/posix/posix.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/router.go
Changed object tag related actions(PutObjectTagging, GetObjectTagging, DeleteObjectTagging) names and some more minor cleanup
> Object tag related actions cleanup

- cmd/versitygw/test.go
- integration/group-tests.go
- integration/tests.go
- s3api/controllers/base.go
1. Created a new test sub-command  and a couple of tests for testing posix specific behaviors.
> Posix specific integration test group

- cmd/versitygw/gateway_test.go
- cmd/versitygw/main.go
- cmd/versitygw/posix.go
- cmd/versitygw/s3.go
- cmd/versitygw/scoutfs.go
- integration/tests.go
- integration/utils.go
This reconfigures the integration tests a bit to be called as unit tests. This makes debugging failing tests a little easier.
> feat: allow integrations tests to be called as unit tests

- auth/iam_proxy.go
- backend/s3proxy/s3.go
- cmd/versitygw/main.go
1. Created Admin CLI actions in s3 proxy
2. Implemented IAM proxy for s3 proxy server
> S3 proxy admin actions

- backend/azure/azure.go
- cmd/versitygw/azure.go
- go.mod
- go.sum
This is the recommended auth from the following:
https://github.com/Azure-Samples/storage-blobs-go-quickstart/blob/master/storage-quickstart.go https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go?toc=%2Fazure%2Fdeveloper%2Fgo%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fgo%2Fbreadcrumb%2Ftoc.json&tabs=roles-azure-portal#authenticate-to-azure-and-authorize-access-to-blob-data
> feat: add azure local env auth

- cmd/versitygw/test.go
- integration/group-tests.go
- integration/tests.go
- s3api/controllers/base.go
Added support to add bucket acl on bucket creation.
Added integration tests for this.
> Bucket ACL on bucket creation

- auth/acl.go
- auth/iam.go
- auth/iam_cache.go
- auth/iam_ldap.go
- cmd/versitygw/admin.go
- s3api/controllers/admin.go
- s3api/middlewares/acl-parser.go
Added a new userplus role in IAM, who may has the same access rules as the user, but can also create a bucket
> IAM userplus role

- cmd/versitygw/admin.go
- cmd/versitygw/test.go
- integration/group-tests.go
- integration/tests.go
- integration/utils.go
- runtests.sh
1. Added IAM integration tests
2. Added iam and posix tests in github pipelines
> IAM integration tests

- backend/backend.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/acl-parser.go
The following actions implementation in FE
1. PutBucketPolicy
2. GetBucketPolicy
> Bucket policy actions FE

- cmd/versitygw/main.go
> fix: return success exit status if shutdown succeeds

- cmd/versitygw/main.go
> fix: require root credentials be set to start gateway

- s3api/utils/utils.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> fix: escape path and query for presign signature validation

- backend/scoutfs/scoutfs.go
There was a change a while back in the aws sdk that made these pointers instead of ints. We somehow missed the pointer deref in the scoutfs backend.
> fix: scoutfs backend needs to dereference types.CompletedPart.PartNumber

- cmd/versitygw/main.go
Fixes #359. This adds the pprof listening endpoint when configured. The option requires providing the listening port. Once enabled, pprof debug utilities are provided at this endpoint.
For example, adding to following option:
--pprof 127.0.0.1:9999
Creates a listener on localhost port 9999. You can then point a browser to http://localhost:9999/debug/pprof/ to get access to the debug utilities.
Another useful case is to get goroutine stack traces live with the following:
curl 'http://localhost:9999/debug/pprof/goroutine?debug=1'
> feat: add optional pprof debug endpoint

- cmd/versitygw/main.go
- s3event/event.go
- s3event/kafka.go
- s3event/nats.go
- s3event/webhook.go
- s3log/file.go
- s3log/webhook.go
1. Added webhook URL support for bucket event notifications
2. Fixed a couple of bugs in event sender and audit logger interfaces
3. Made some refactoring in event sender interface
> Bucket event notifications with webhook URL

- cmd/versitygw/main.go
- cmd/versitygw/test.go
- cmd/versitygw/utils.go
- s3api/controllers/base.go
- s3event/event.go
- s3event/filter.go
- s3event/kafka.go
- s3event/nats.go
- s3event/webhook.go
1. Implemented the filter logic for bucket event notifications with a config file.
2. Created a utility CLI command to create event filters config file.
> Bucket event notifications filters

- extra/example.conf
This adds some new setting options and explanations to the example service config.
> feat: add new config options to example

- cmd/versitygw/admin.go
Fixes #499. Allows running admin cli commands against servers with self signed certs.
> feat: optional disable cert check for admin cli actions

- s3api/controllers/base.go
- s3api/controllers/base_test.go
- tests/integration/tests.go
> HeadBucket response headers

- Dockerfile.dev
- backend/azure/azure.go
- docker-compose.yml
Implemented PutBucketPolicy, GetBucketPolicy actions
> Azure bucket policy actions

- README.md
Move use cases up, and change wording. Add link for global options in the wiki.
> chore: minor readme cleanup

- backend/azure/azure.go
Object lock actions implementation in azure backend
> Azure object lock actions

- backend/s3proxy/s3.go
Bucket policy and object lock actions implementation in s3 proxy.
> S3 proxy bucket policy, object lock actions

- cmd/versitygw/utils.go
- s3api/controllers/base.go
- s3event/event.go
- s3event/filter.go
- s3event/kafka.go
- s3event/nats.go
- s3event/webhook.go
Added support to send bucket event notifications for DeleteObjects action
> Bucket event notifications DeleteObjects

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- s3response/s3response.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Added GetObjectAttributes action implementation in the following backends.
1. Azure
2. Posix
3. S3 proxy
Added some integration test cases for it.
> GetObjectAttributes action

- backend/posix/posix.go
- s3api/controllers/base.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Implemented HeadObject action muliipart uploaded object case.
> HeadObject action multipart upload case

- auth/acl.go
- cmd/versitygw/main.go
- s3api/admin-server.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/acl-parser.go
- s3api/router.go
- s3api/router_test.go
- s3api/server.go
> Gateway readonly mode

- backend/azure/azure.go
- backend/posix/posix.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
> PutObjectLockConfiguration default disabled object lock

- auth/object_lock.go
- tests/integration/tests.go
> PutObjectLockConfiguration both years and days specified

- auth/object_lock.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> PutObjectLockConfiguration days & years validation

- auth/object_lock.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> PutObjectLockConfiguration status & mode props validation

- s3api/controllers/base.go
- s3api/controllers/base_test.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> PutObjectLegalHold status validation

- backend/azure/azure.go
- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> CreateBucket BucketAlreadyOwnedByYou error

- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
> GetObject by range success response status code

- auth/bucket_policy_principals.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> Bucket policy principal structure fix

- backend/posix/posix.go
- s3api/controllers/base.go
- s3api/utils/utils.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> CreateMultipartUpload missing properties support

- auth/object_lock.go
- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/test_aws.sh
> WORM protection root/admin users

- backend/common.go
- tests/integration/tests.go
> GetObject same range fix

- s3api/controllers/base.go
- s3api/controllers/base_test.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> Bucket ACL required request body fix

- backend/posix/posix.go
- tests/integration/tests.go
> GetObject exceeding range

- s3api/controllers/base.go
> Copy object storage class

- auth/iam_internal.go
- auth/iam_s3_object.go
Add a mutex to prevent reacing accounts updates from multiple simultaneous account update requests.
This mutex will help with racing updates to the IAM data from multiple requests to this gateway instance, but will not help with racing updates to multiple load balanced gateway instances. This is a limitation of the internal IAM service. All account updates should be sent to a single gateway instance if possible.
fixes #630
> fix: internal iam racing account updates causing inconsistencies

- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
> Admin api error response statuses

- backend/common.go
- backend/posix/posix.go
- tests/integration/tests.go
> UploadPartCopy exceeding range error

- auth/bucket_policy.go
- auth/bucket_policy_actions.go
- auth/bucket_policy_effect.go
- auth/bucket_policy_principals.go
- auth/bucket_policy_resources.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/test_aws.sh
Fixes #645
Fixes #646
Fixes #647
Fixes #648
Fixes #649
Fixes #650
> Bucket policy validation error messages

- tests/versity.sh
This is a fairly minimal change to add support for ScoutFS as a test backend. Note that this isn't runnable via github actions due to filesystem requirements.
> test: add new test backend for ScoutFS

- backend/azure/azure.go
- backend/backend.go
- backend/common.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/scoutfs/scoutfs.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- tests/integration/tests.go
Implemented response body streaming for GetObject action.
Fixes #657 .
> GetObject response body streaming

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/backend_moq_test.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #667
Fixes #668 
Fixes #669
Fixes #670
> ChangeBucketOwner acl update

- cmd/versitygw/main.go
- s3api/admin-router.go
- s3api/admin-server.go
- s3api/controllers/admin.go
- s3api/router.go
- s3api/router_test.go
- s3api/server.go
- s3api/server_test.go
- s3log/audit-logger.go
- s3log/file_admin.go
Implemented access logs for admin APIs.
Closes #642
> Admin APIs access logs

- backend/azure/azure.go
- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
> CopySource parsing starting with '/' for CopyObject action

- backend/scoutfs/scoutfs.go
Files created outside of versitygw can be missing etag attributes. Allow the empty etag to not cause errors with listing the files.
Fixes #694
> fix: allow objecting listing in scoutfs for files created without etag attrs

- auth/iam.go
- auth/iam_internal.go
- auth/iam_ldap.go
- auth/iam_s3_object.go
- auth/iam_vault.go
- cmd/versitygw/main.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Added the root user credentials in IAM records.
Fixes #693 
Fixes #691 
Fixes #716 
Fixes #695
> Root user credentials in IAM services

- backend/azure/azure.go
The container URL was adding an extra / when the service URL ended with /. This results in an invalid container URI error from Azure.
This also fixes the container metadata keys to not include "-" that the Azure service disallows. The metadata values are base64 encoded to prevent any special chacter handling on Azure service side.
The content type is set for uploads consistent with S3 expectations.
Fixes #736
> fix: azure backend errors with storage url and container metadata

- cmd/versitygw/main.go
This changes the startup banner to report the versitygw version and build info along with interfaces configured for admin and s3 services when quiet option not enabled.
Fixes #728
> feat: change startup banner to versitygw version

- .gitignore
- backend/azure/azure.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes couple of bugs in azure including LlistObjects(V2), CopyObject, Object lock related and other actions.
Implemented multipart upload with .sgwtmp namespace in azure backend. The implementation uses the namespace to store multipart uploads metadata. The multipart upload parts are stored as uncommitted blocks in a block blob.
> Azure integration test issues

- auth/iam.go
- cmd/versitygw/admin.go
- metrics/actions.go
- s3api/admin-server.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/middlewares/admin.go
- s3api/router.go
- s3err/s3err.go
- s3response/s3response.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #848 .
Admin APIs refactoring:
1. Updates data transfer encoding to XML for improved compatibility.
2. Implements AWS-style error handling.
3. Adds a middleware to verify admin roles.
4. Modifies admin CLI actions to handle AWS-style error responses.
> Admin APIs refactoring

- auth/iam_ipa.go
Some minor code cleanup and removal of extra print output.
> fix: minor code cleanup for ipa iam

- backend/s3proxy/s3.go
For s3 proxy backend, the ACLs are stored in bucket tags to not conflict with the underlying s3 object store ACLs. If the tag for the gatway ACLs does not exist for the bucket, then we were incorrectly returning the NoSuchTagSet from teh tag lookup. Instead, in this case we need to just return the default gateway bucket ACL, which is the root account ownership.
Side note that there is currently a bug in the go sdk where the NoSuchTagSet is not defained as an error type, and a workaround for string matching is required until this is addressed. https://github.com/aws/aws-sdk-go-v2/issues/2878
> fix: s3proxy get bucket acl when no acl exists in s3 service

- s3api/utils/utils.go
- tests/integration/tests.go
Fixes #1186
Fixes #1188
Fixes #1189
If multiple checksum headers are provided, no matter if they are empty or not, the gateway should return `(InvalidRequest): Expecting a single x-amz-checksum- header. Multiple checksum Types are not allowed.` An empty checksum header is considered as invalid, because it's not valid crc32, crc32c ...
> fix: Handles the error cases for empty checksum headers for PutObject and UploadPart

- backend/posix/with_otmpfile.go
- backend/scoutfs/scoutfs_compat.go
We had put the error handling in for the read only filesystems when O_TMPFILE is supported, but missed the CreateTemp() fallback case. This fixes this case to also return the method not allowed error.
This also adds the error handling for the scoutfs case as well.
Fixes #1195
> fix: return method not allowed for read only fs for fallback tempfile

- s3api/utils/signed-chunk-reader.go
Fixes #1238
The signed chunk reader stashes the header bytes if it can't fully parse the chunk header. On the next `io.Reader` call, the stash is combined with the new buffer data to attempt parsing the header again. The stashing logic was broken due to the premature removal of the first two header bytes (`\r\n`). As a result, the stash was incomplete, leading to parsing issues on subsequent calls.
These changes fix the stashing logic and correct the buffer offset calculation in `parseChunkHeaderBytes`.
> fix: fixes the signed chunk encoding reader stashing.

- backend/s3proxy/s3.go
Provide an alternate S3Proxy initialization using a provided s3.Client instance to support more advanced configuration.
> Add support for supplying s3.Client instance to S3 Proxy

- backend/posix/posix.go
Fixes #1233
Add double quotes to the `ETag` in `UploadPart`.
> fix: adds quotes to part Etag in UploadPart

- s3api/debuglogger/logger.go
Fixes #1253
Removes the xml pretty printing from debug logger. Instead it prints out the raw request/response body. This way we avoid to miss/add something to raw xml, which could lead to misconfusion.
> fix: removes the xml pretty printing from debug logger.

- auth/iam_internal.go
This cleans up a previous fix to #630 to use a better temp/rename scheme thats less likely to have bad side effects.
The test for the previous issue still passes these cases, and we will be less liekly to find a case where the file doesnt exist or corrpted backup files.
> fix: use createtemp()/rename() for iam internal files

- s3api/controllers/base.go
On 32-bit systems, this value could overflow. Add a check for the overflow and return ErrInvalidRange if it does overflow.
The type in GetObjectOutput for ContentLength is *int64, but the fasthttp.RequestCtx.SetBodyStream() takes type int. So there is no way to set the bodysize to the correct limit if the value overflows.
> fix: add bounds check for ContentLength type conversion

- backend/walk.go
Common prefixes were originally stored in a `map[string]struct{}`, which was then converted to a slice and sorted. The new implementation stores the common prefixes in a `map[string]int`, where the map value represents the index of the common prefix. There's no need to sort the common prefixes array, as `fs.WalkDir` comes with sorted directories and files.
> feat: optimizes backend.Walk and backend.WalkVersions to avoid sorting the common prefixes.

- backend/s3proxy/s3.go
This fixes the listing of buckets when multi tenant mode is enabled with a metadata bucket. The following behavior changes are fixed:
* prevent listing of metadata bucket by all accounts
* prevent listing of non-owned buckets by user/userplus
* return correct BucketAlreadyExists/BucketAlreadyOwnedByYou for attempts to create existing bucket
Fixes #1326
> fix: s3 backend user bucket listing

- backend/posix/posix.go
This fixes a panic seen when there were a lot of multipart uploads in the same bucket requiring multiple paginated responses. for example:
```
panic: runtime error: index out of range [11455] with length 1000 goroutine 418 [running]:
github.com/versity/versitygw/backend/posix.(*Posix).ListMultipartUploads(0xc0004300 
/Users/ben/repo/versitygw/backend/posix/posix.go:2122 +0xd25 
github.com/versity/versitygw/s3api/controllers.S3ApiController.ListActions({{0x183c
...
```
This change updates the ListMultipartUploads implementation to properly advance past the (KeyMarker, UploadIDMarker) tuple when paginating, ensuring that each response starts after the marker and does not include duplicate uploads.
> fix: ListMultipartUploads pagination panic and duplicate results

- backend/posix/posix.go
The `GetObject` call may return wrong metadata (even checksum and content-length) when an upload to an existing object is running concurrently. 
Testing: 
- Run concurrent upload (in infinite loop) of 3 files of different size into the same Key, include some checksum with the upload
- Try to read the Key and check the checksum. Occasionally a checksum doesn't fit the data (probably because a wrong content-length is used for the data)
- This test may also fail with 404, which is a separate problem, so if you are running this on Linux, it's necessary to disable build of `./backend/posix/with_otmpfile.go` and use `./backend/posix/without_tmpfile.go`.
This PR seems to solve the problem. I'm not an expert in Go and don't know the codebase, so take it more as an inspiration, but it seems to me …
> Fix race in GetObject

- auth/iam_ldap.go
Handle LDAP connection failures by attempting to reconnect. This should resolve the issue of connections being closed by the LDAP server after a period of inactivity.
Fixes #1464
> fix: iam ldap reconnect after network disconnects

- backend/s3proxy/s3.go
The CORS actions were directly proxied in s3 proxy backend. The new implementation stores/retrieves/deletes bucket cors configuration in `meta` bucket.
> feat: changes cors implementation in s3 to store/retrieve in meta bucket

- s3api/server.go
Fixes #1426
Fiber returns a custom error, if it fails to parse the `Content-Length` header. This implementation adds a check in the fiber global error handler to return an empty `400` Bad Request error, if fiber fails to parse the `Content-Length` header.
> fix: fixes the invalid Content-Length error
