- backend/common.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_darwin.go
- backend/scoutfs/scoutfs_linux.go
- backend/scoutfs/scoutfs_windows.go
- cmd/versitygw/main.go
- cmd/versitygw/scoutfs.go
- go.mod
- go.sum
ScoutFS has an ioctl to move extents from one file to another with only metadata updates.  We can leverage this for multipart upload optimizations to move the data from the part into the final object without having to copy any data around.
This also adds the new scoutfs backend type in the cli for scoutfs specific enhancements.
> feat: scoutfs backend with move blocks multipart optimized

- backend/common.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- integration/tests.go
- integration/utils.go
The aws cli will send range gets of an object with ranges like the following:
bytes=0-8388607
bytes=8388608-16777215
bytes=16777216-25165823
bytes=25165824-
The last one with the end offset unspecified just means the rest of the object. So this fixes that case where there is only one offset in the range.
> fix range gets with unspecified end range

- cmd/versitygw/main.go
- cmd/versitygw/signal.go
- s3log/audit-logger.go
- s3log/file.go
- s3log/webhook.go
This also cleans up some the of the error output to send to stderr.
This adds the Shutdown() to the logging interface, so we can keep the log file open and just append entries.
This add HangUp() to the logging interface for log rotations.
> fix: allow logging to user specified log files

- integration/action-tests.go
- integration/tests.go
- integration/utils.go
- s3api/controllers/base_test.go
- s3api/middlewares/authentication.go
- s3err/s3err.go
1. Added new error cases in the authentication to make it more compatible with aws.
2. Created integration test cases for authentication.
Here is the [resource](https://docs.aws.amazon.com/IAM/latest/UserGuide/signature-v4-troubleshooting.html#signature-v4-troubleshooting-credential-scope) for SigV4 errors.
> Authentication errors refactoring

- auth/iam.go
- auth/iam_internal.go
- cmd/versitygw/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/iam_moq_test.go
We don't want to expose the UserAcct in the interface, so we should just reuse the Account struct here.
> fix: move auth internal UserAcc to auth.Account

- backend/backend.go
- backend/posix/posix.go
- integration/action-tests.go
- integration/tests.go
- integration/utils.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
1. Changed ListBuckets action logic to return all the buckets for admin users.
2. Change the logic for ListBuckets to return only the buckets owned by a user for regular users.
3. Added integration test cases for ListBuckets action
> Issue 204, ListBuckets for admin and regular users

- cmd/versitygw/main.go
The BodyLimit is needed for large PUTs in the s3 api server, but the admin server requests are not expected to exceed the default 4MB limit.
> fix: remove body limit for admin app

- backend/walk.go
- integration/action-tests.go
- integration/tests.go
- integration/utils.go
1. Fixed marker bug, when specifying max-items next-marker should be the last object key in the list
2. When listing the objects with marker, the listing has to start after the specified marker object not including the one
> Issue 179, 180

- backend/walk.go
There's a case when it finds an object but it's saved as delimiter and objects slice is empty, which causes the app panic. Just changed the implementation of checking the last element existence.
> Walk function last object check panic fix

- backend/posix/posix.go
- integration/action-tests.go
- integration/tests.go
- s3api/controllers/base.go
Added destination bucket ACL check for CopyObject action. It return 403 Forbidden if the requester's access isn't included in the ACL.
> Issue 244, Destination bucket ACL check for CopyObject action

- backend/posix/posix.go
- integration/action-tests.go
- integration/tests.go
- integration/utils.go
- s3api/controllers/base.go
Added maximum length check for tag keys and values in PutObject and PutObjectTagging.
> Issue 246, tag maximum length check for PutObject and PutObjectTagging actions

- backend/walk.go
- integration/action-tests.go
- integration/tests.go
1. Changed ListObjects(V2) implementation, so if user provides a marker that is not included in the existing objects list, action returns the objects keys, which are lexicographically higher than the provided
> Issue 250, ListObjects(V2) marker not from objects list.

- backend/backend.go
- backend/posix/posix.go
- backend/walk.go
- integration/action-tests.go
- integration/tests.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/router.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
CopyObject copies the object with new metadata provided. Added a comparison step for metadata, if a user tries to copy the object to itself, it is allowed if the metadata has been changed.
> CopyObject metadata

- backend/posix/posix.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
AWS CLI sends meta headers like this: x-amz-meta-(lowercased)
AWS SDK sends meta headers like this: X-Amz-Meta-(uppercase)
Changed the implementation so the gateway could store/get metadata in both cases.
> Issue 274, Object metadata normalization

- auth/iam.go
- auth/iam_cache.go
- auth/iam_internal.go
- auth/iam_ldap.go
- auth/iam_single.go
- cmd/versitygw/main.go
- s3api/controllers/iam_moq_test.go
The local IAM accounts were being cached in memory for improved performance, but this can be moved up a layer so that the cache can benefit any configured IAM service.
This adds options to disable and tune TTL for cache. The balance for the TTL is that a longer life will send requests to the IAM service less frequently, but could be out of date with the service accounts for that duration.
> feat: move local iam cache to a more generic cache mechanism

- auth/acl.go
- auth/iam_single.go
- backend/s3proxy/client.go
- backend/s3proxy/s3.go
- cmd/versitygw/main.go
- cmd/versitygw/s3.go
This backend redirects incoming requests to another s3 service. This will use the incoming credentials to setup the client requests to the external s3 service. So the IAM accounts (or root account) must match what the external s3 service expects.
> feat: s3proxy backend

- .goreleaser.yaml
We were getting the following error on el7:
$ ./versitygw -h
./versitygw: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./versitygw) ./versitygw: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./versitygw)
The temporary fix is to disable cgo in the builds per this issue: https://github.com/golang/go/issues/58550
We will need to visit per distro builds once we need to re-enable cgo.
> fix: fixes #311 - disable cgo in release builds

- backend/s3proxy/client.go
- backend/s3proxy/s3.go
- cmd/versitygw/s3.go
The previous way of initializing the s3 client in each call was adding a lot of overhead and would tank performance beyond about 20 simultaneous requests.
Since the backend access is through a single account, we can init and store this client for use from each api call.
> fix: s3 backend performance increase with client reuse

- backend/azure/azure.go
This comment references a bug that was fixed in the v1.2.1 sdk update:
https://github.com/Azure/azure-sdk-for-go/issues/22171
> chore: remove azure bug comment

- backend/azure/azure.go
- cmd/versitygw/azure.go
Added support to add sas token to the URL to get access to some resources with the token
> Azure sas token authentication

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
This adds the default ACL to the CreateBucket backend method so that the backend doesn't need to know how to construct and ACL.
This also moves the s3proxy ACLs to a tag key/value because the gateway ACLs are not the same accounts as the backend s3 server. TODO: we may need to mask this tag key/value if we add support for the Get/PutBucketTagging API.
> fix: cleanup backend ACLs

- s3api/utils/auth-reader.go
- s3api/utils/auth_test.go
This change removes all spaces after the algorithm to have standard parsing for the following key/value pairs. This fixes some clients that were using a slightly different format than the example AWS request strings.
> fix: allow spaces in Authorization string

- s3api/middlewares/chunk.go
- s3api/server.go
- s3api/utils/chunk-reader.go
As described in
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html this adds support for reading from a chunked upload encoded request body. The chunked reader modifies the data stream to remove the chunk encoding while validating the chunk signatures in line. This allows the upper layers to get just the object data stream.
> feat: add chunked upload support

- backend/backend.go
- backend/posix/posix.go
- cmd/versitygw/test.go
- integration/group-tests.go
- integration/tests.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/acl-parser.go
Added support for the following actions in posix backend
1. PutBucketTagging
2. GetBucketTagging
3. DeleteBucketTagging
proxy acl is stored in a separate xattr key, to differentiate the tags from acl.
> Bucket tagging actions

- integration/group-tests.go
- integration/tests.go
- integration/utils.go
- s3api/middlewares/authentication.go
- s3api/middlewares/presign-auth.go
- s3api/server.go
- s3api/utils/presign-auth-reader.go
- s3api/utils/presign-auth-reader_test.go
- s3api/utils/utils.go
Added support for presigned URLs: v4 authentication with query params.
Example using presigned URL with AWS CLI: [aws cli](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/presign.html)
A sample to get started
```
aws --endpoint-url http://localhost:7070 s3 presign s3://my-bucket/my-object  --expires-in 604800
```
The above CLI actions generates a presigned URL to get `my-object` from `my-bucket`
Examples using presigned URLs with AWS SDK Go: [aws sdk](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_PresignedUrl_section.html)
> Presigned URL authentication

- .goreleaser.yaml
This fixes the location of the release binary to the top level for better release artifact locations.
> chore: fix releaser build path

- README.md
We have good general client test coverage now. So we can bring this out of testing status.
> chore: update readme to remove the testing status

- s3api/controllers/base.go
Fixes #444. For some clients using chunked uploads with a zero length file, the content length value from the request headers was coming back as an empty string. If this happens, just set it to "0" so that we can successfully parse this to int value.
> fix: zero len put error when content length value not defined

- s3api/controllers/base.go
- s3response/s3response.go
Fixes #447. Previously we required XML namespace and got these errors with this input:
DEBUG:  <Tagging><TagSet><Tag><Key>mykey</Key><Value>myvalue</Value></Tag></TagSet></Tagging>
DEBUG: expected element <Tagging> in name space http://s3.amazonaws.com/doc/2006-03-01/ but have no name space
> fix: remove namespace restrictions on tag xml input

- s3api/utils/auth_test.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
Fixes #457. There are some buggy clients that include headers not actually set on the request in the signed headers list. For these we need to include them in the signature canoncal string with empty values.
> fix: include all request signed headers in signature canonical string

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- s3err/s3err.go
When fileystem quota exceeded, the gateway will now return the error:
S3 error: 403 (QuotaExceeded):
Your request was denied due to quota exceeded.
This will help clients to better detect upload errors due to quota exceeded.
Fixes #483
> feat: add s3err QuotaExceeded for posix/scoutfs

- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/router.go
- s3api/router_test.go
- s3api/server.go
There are a few cases where parsing, validations checks, etc error details are getting lost with the more generic error responses. This add some opt-in debug logging to log more info for these various error cases.
> feat: add more debug logging for api handler errors

- cmd/versitygw/admin.go
- s3api/controllers/admin.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #505. This returns the body as an error when the http status for the admin request is non-success.
> fix: return non 0 exit status for cli admin error

- backend/meta/meta.go
- backend/meta/xattr.go
- backend/meta/xattr_with_enodata.go
- backend/meta/xattr_without_enodata.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs_compat.go
- cmd/versitygw/gateway_test.go
- cmd/versitygw/posix.go
Closes #511. This adds an abstraction layer to the metadata storage to allow for future non-xattr metadata storage implementations.
> feat: add metadata storage abstraction layer

- s3api/utils/chunk-reader.go
Fixes #512. For chunked uploads, we parse the chunk headers in place and then move the data payload up on the buffer to overwrite the chunk headers for the real data stream.
For the special case where the chunk header was truncated in the current read buffer, the partial header is stashed in a temporary byte slice. The following read will contain the remainder of the header that we can put together and parse.
We were correctly parsing this, but we forgot that the data offset is calculated based on the start of the header. But the special case where part of the header was stashed means we were incorrectly calculating the data offset into the read buffer.
Easy fix to just remove the stash size from the data offset return value.
> fix: chunkreader invalid signature when header crossed read buffers

- auth/iam_single.go
Fixes #524. The iam single needs to return ErrNoSuchUser instead of ErrNotSupported in GetUserAccount to return the correct error when the client access is not done by the single user account.
This fixes the internal error when accessing the gateway in iam single user mode with incorrect access keys.
> fix: auth iam single error for GetUserAccount()

- go.mod
Setting min toolchain to 1.21.0 for the gateway.
see: https://go.dev/doc/toolchain#version
> fix: as of Go 1.21, toolchain versions must use the 1.N.P syntax

- s3api/utils/chunk-reader.go
Make the code scanners happy with a bounds check before we do the integer conversion from int64 to int, since this can overflow on 32 bit platforms.
> fix: int overflow check in chunk reader

- auth/acl.go
- auth/bucket_policy.go
- auth/object_lock.go
- backend/azure/azure.go
- backend/posix/posix.go
- s3api/controllers/base.go
- s3err/s3err.go
- tests/commands/get_bucket_policy.sh
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/test_common.sh
- tests/util.sh
- tests/util_policy.sh
1. AWS error refactoring
2. Added support to enable object lock on bucket creation in posix and azure backends.
3. Implemented the logic to add object legal hold and retention on object creation in azure and posix backends.
4. Added the functionality for HeadObject to return object lock related headers in posix.
5. Added couple of integration tests for these features.
> AWS error refactoring

- s3api/controllers/base.go
CopyObject action response body has `CopyObjectResult` type.
In terms of Go SDK it's `s3.CopyObjectOutput.CopyObjectResult`.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#AmazonS3-CopyObject-response-CopyObjectResult
> CopyObject response body type

- backend/posix/posix.go
This fixes a bug where s3fs-fuse doesn't recognize directories served by versitygw
versitygw is sending back (at least on my filesystem) a media type of text/plain and a size of 4096.  s3fs is looking for one of these:
* media type "application/x-directory"  (which I believe is used by AWS and Nextcloud)
* media type "httpd/unix-directory"
* a non-empty string ending with "/" and
* media type "binary/octect-stream" or "application/octet-stream"  or
* media type "text/plain" and size == 0 or 1
Since none of those match, directories are returned as regular files and can't be used.
This patch sets the media type to "application/x-directory" to ensure directories are recognized.
> Set the media type for directories

- backend/posix/posix.go
- backend/posix/with_otmpfile.go
- backend/posix/without_otmpfile.go
The complete multipart upload can be optimized in some cases to not need to copy the full data from parts to the final object file. If the filesystem supports it, there can be optimizations to just clone exent references and not have to actually copy the data.
For io.Copy() to make use of file_copy_range, we have to pass it the *os.File file handles from the filesystem for the source and destination. We were previously adding a layer of indirection that was causing io.Copy() to fallback to full data copy. This fixes the copy by exposing the underlying fd.
This also skips the falloc for the final object in complete mutlipart upload, because some filesystems will be able to use file_copy_range to optimize the copy and may not even need new data allocations in the final object file.
Note …
> fix: expose posix tmpfile fd to enable copy_file_range

- auth/iam.go
- auth/iam_internal.go
- auth/iam_s3_object.go
- cmd/versitygw/admin.go
The intent was to have a project id that could be set along with user and group ids for new files/objects in the backend. However, most filesystems don't actually associate a project with a user, and instead have the project id inherited from parent directories.
Let's remove the project id for now, and we can always bring it back if we have a backend that will be able to make use of it.
> fix: remove unused project id in account info

- cmd/versitygw/utils.go
This adds indent fomratting to the generated event_config.json for easier reading/editing.
> fix: use json.MarshalIndent to format event_config.json

- auth/iam_internal.go
- auth/iam_s3_object.go
There were a couple of cases where parsing the stored IAM info could return a config with a nil map that would panic in a future assignment. So we just need to make sure there is an initialized map when we return the config with no error set.
> fix: init auth config accounts map

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
Add meta.MetadataStorer compatibility to scoutfs so that scoutfs is using the same interface as posix. This fixes the metadata retrieval and adds the recently supported object lock compatibility as well.
> fix: correct metadata, tags, and lock info for scoutfs multipart objects

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Azure backend bug fixing.
Azure backend incompatible parts with AWS are listed below:
1.  `Multipart Upload`: Multipart upload starts with `UploadPart` action, which causes some tests to fail.
2. `UploadPartCopy`: `StageBlockFromURL` (azure sdk) method is used to handle `UploadPartCopy` action, which returns NotImplemented on azurite.
3. `ListObjects(V2)` doesn't support delimiter.
4. `ListBuckets` doesn't return all the buckets for admin/root users, only the ones owned by the requester.
> Azure bug fixing

- backend/scoutfs/scoutfs_compat.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
The restore object api request handler was incorrectly trying to unmarshal the request body, but for the stadnard (all?) case the request body is emtpy. We only need the bucket and opbject params for now.
This also adds a fix to actually honor the enable glacier mode in scoutfs.
> fix: restore object request handler and scoutfs glacier enable

- backend/posix/posix.go
In the posix backend, the path argument to os.RemoveAll() does not start with the bucket name. Since the path does not exist, os.RemoveAll() does nothing and uploaded parts are left in the ".sgwtmp" directory.
This commit prefixes the path with the bucket name.
Fixes issue #626.
> fix: fix removal of the upload directory in posix CompleteMultipartUpload

- backend/azure/azure.go
Changed ListBuckets action implementation to return all the buckets for admin users and only the ones owned by the requester for regular users.
If the following configuration is not provided for `ListContainersPager`, it clears container `metadata`. This is probably an sdk bug or the problem appears in azurite.
```
&service.ListContainersOptions{
Include: service.ListContainersInclude{
Metadata: true,
},
}
```
> Azure ListBuckets for different users

- auth/iam.go
- auth/iam_cache.go
- auth/iam_internal.go
- auth/iam_ldap.go
- auth/iam_s3_object.go
- auth/iam_single.go
- auth/iam_vault.go
- cmd/versitygw/admin.go
- cmd/versitygw/main.go
- s3api/admin-router.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/iam_moq_test.go
- s3api/router.go
> IAM update user account

- tests/test_aws.sh
- tests/test_common.sh
Some backends require larger part sizes for the multipart upload
tests. Increase the test file size to 5M to meet the requirements
for scoutfs.
> test: increase test file sizes to 5M for larger part sizes

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- backend/walk.go
- backend/walk_test.go
For large directories, the treewalk can take longer than the client request timeout. If the client times out the request then we need to stop walking the filesystem and just return the context error.
This should prevent the gateway from consuming system resources uneccessarily after an incoming request is terminated.
> fix: cancel filesystem traversal when listing request cancelled

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
- cmd/versitygw/posix.go
- cmd/versitygw/scoutfs.go
- extra/example.conf
This adds the ability to treat symlinks to directories at the top level gateway directory as buckets the same as normal directories.
This could be a potential security issue allowing traversal into other filesystems within the system, so is defaulted to off. This can be enabled when specifically needed for both posix and scoutfs backend systems.
Fixes #644
> feat: add option to allow symlinked directories as buckets

- auth/acl.go
- s3api/controllers/admin.go
- s3api/controllers/base.go
- s3api/server.go
- tests/integration/tests.go
- tests/integration/utils.go
Added the `Type` property support in the `Grantee` schema for bucket ACLs. Hardcoded `Type` to `CanonicalUser` for iam users and `Group` for `all-users`.
Fixes #651,
Fixes #664
> Type property support in bucket ACL

- auth/acl.go
- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Removed the bucket ACL owner check for admin/root users.
Fixes #680
> Bucket ACL owner check for admin/root users

- s3api/controllers/base.go
- tests/integration/tests.go
AWS uses binary/octet-stream for the default content type if the client doesn't specify the content type. Change the default for the gateway to match this behavior.
Fixes #697
> fix: set default content type to binary/octet-stream

- backend/posix/posix.go
- tests/integration/tests.go
The expected response code for deleting non-existing objects is expected to be 204 (No Content) instead of NoSuchKey. The tests are updated to validate expected responses.
Fixes #724
> fix: non-existing object delete response

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base_test.go
- s3response/s3response.go
Fixes #738 
Changed CreateMultipartUpload action return type from `*s3.CreateMultipartUploadOutput` to `*s3response.InitiateMultipartUpload`.
> CreateMultipartUpload return type fix

- backend/posix/posix.go
The admin/root user has access to all buckets. So we don't need a valid ACL defined on the bucket to list these. Treat a non-existing ACL as an empty ACL for this case.
Fixes #727
> fix: allow listing buckets without acl attribute

- backend/posix/posix.go
- backend/walk.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #740 
Changed the directory objects listing implementation to include them in common prefixes when the object name includes the specified delimiter.
> Directory objects listing with delimiter

- s3api/controllers/base.go
When on linux with O_TMPFILE support, we issue and fallocate for the expected object size ax an optimization for the underlying filesystem to allocate the full file all ate once. With the chunked transfer encoding, the final object size is recoded in the X-Amz-Decoded-Content-Length instead of the standard ContentLength which includes the chunk encoding in the payload.
We were incorrectly using the content length to fallocate the file which would cause the filesystem to pad out any unwritten length to this size with 0s.
The fix here is to make sure we pass the X-Amz-Decoded-Content-Length as the object size to the backend for all PUTs.
Fixes #753
> fix: put file corruption with chunked transfer

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
The posix limits wont exactly match up with the AWS key length limits because posix has component length limits as well as path length limits.
This reponds with the aws compatible KeyTooLongError under these conditions now.
Note that delete object returns success even in the error cases.
Fixes #755
> fix: return KeyTooLongError when filenames exceed allowed length

- cmd/versitygw/main.go
Fiber allows for dual stack ipv4/ipv6 by setting Network setting to fiber.NetworkTCP. The default is fiber.NetworkTCP4 which is ipv4 only because the dual stack is not compatible with prefork. But we do not use prefork, so it is fine to enable the dual ipv4/ipv6 support.
> feat: enable ipv6 support for listening socket

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/scoutfs/scoutfs.go
- backend/walk.go
- backend/walk_test.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3response/s3response.go
Fixes #752 
Changed ListObjectsV2 and ListObjects actions return types from *s3.ListObjects(V2)Output to s3response.ListObjects(V2)Result. 
Changed the listing objects timestamp to `RFC3339` to match AWS S3 objects timestamp.
> ListObjects & ListObjectsV2 return types

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/scoutfs/scoutfs.go
- backend/walk_test.go
- s3response/s3response.go
It is better if we let the s3response module handle the xml formatting spec specifics, and let the backends not worry about how to format the time fields. This should help to prevent any future backend modifications or additions from accidental incorrect time formatting.
> fix: move RFC 3339 time formatting to s3response

- backend/walk.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #763 
When calling the ListObjects(V2) actions with delimiter the results are grouped in common prefixes. 
Fixed the pagination for common prefixes: e.g.
Bucket: my-bucket
Objects: d1/f1, d2/f2, d3/f3, d4/f4
Request syntax: GET /?list-type=2&max-keys=3&delimiter=/
Result:
Common Prefixes: d1/, d2/, d3/
NextContinuationToken: d3/
> ListObjects(V2) common prefixes pagination

- backend/posix/posix.go
This fixes #784.
`removeParents()` gets called when `posix.DeleteObject()` is called. It will iterate through each parent directory of an object path that is being deleted, and it'll also delete that parent unless:
1. The parent is the bucket
2. The parent has a valid etag
3. The parent is not empty (or if `os.Remove()` fails for another reason)
I believe the logic used to check if the parent is the bucket is off.
Currently this is the condition:
```go
parent := filepath.Dir(objPath)
if parent == string(filepath.Separator) {
// stop removing parents if we hit the bucket directory.
break
}
```
Because `objPath` doesn't start with a `/` (relative style), it is impossible for `parent` to ever equal `/`. Instead I think we should test for `.`
Referenced: …
> fix: DeleteObject not working as expected when using `--bucketlinks` (#784)

- backend/posix/posix.go
- tests/integration/tests.go
- tests/integration/utils.go
When using the REPLACE directive, we were incorrectly removing the old metadata on the object due to missing the metadata prefix on the key.  Fix this to remove the correct metadata before setting new metadata.
Fixes #787
> fix: copy object missing prefix on metadata delete

- backend/posix/posix.go
- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
This fixes put object with setting a content type. If no content type is set, then we will return a default content type for following requests. Mutli-part upload appears to be ok.
Fixes #783
> fix: set content type on put object

- s3response/s3response.go
Change all response times to UTC. Fix bucket create date time formatting. This was using the incorrct xml field name before.
> fix: time locale utc in responses

- tests/Dockerfile_direct
- tests/docker-compose-bats.yml
- tests/run_all.sh
The direct tests don't need the gateway or any go compilers. This separates out the dockerfile to minimize it a bit more from the other tests.
> fix: separate out direct tests dockerfile for easier use

- .gitignore
- s3api/middlewares/url-decoder.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- tests/integration/tests.go
- tests/test_s3api.sh
Fixes #781 
Implemented a custom URI path escape mechanism to support most of the characters mentioned in [aws docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html).
The implementation takes the original URI path, escapes it, and then passes it to the HTTP request creation.
> URI path escape

- backend/common.go
- tests/integration/tests.go
- tests/test_aws_root_inner.sh
The range min-max where min=max was incorrectly returning invalid object range.  On AWS, this returns the byte at offset min.
Fixes #810
> fix: get object range min=max return single byte min

- backend/azure/azure.go
- backend/walk.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
This checks to see if the common prefix is before the marker and thus would have been returned in earlier list objects request.
The error case was aws cli listing multiple entries for the same common prefix when the listing required multiple pagination requests.
Fixes #778
> fix: list objects trim common prefixes that match marker prefix

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
The object semantics are that a key that ends with / is different than a key that does not.  However on posix a name that ends with / is assumed to be a directory, but it still succeeds to access the directory by name without a trailing /. So we need to explicitly check if the request is for a non-directory and we are trying to access a directory.
Fixes #824
> fix: requests should fail for directory objects if key does not end in /

- auth/object_lock.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Object lock functionality for bucket versioning had been reverted and removed from versioning PR.
Reverted back the functionality from local copy, fixed merge conflicts with the recent changes and adjusted to the integration tests.
> Object lock for bucket versioning

- auth/object_lock.go
- backend/meta/meta.go
- backend/meta/xattr.go
- backend/posix/posix.go
- backend/posix/with_otmpfile.go
- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
- backend/scoutfs/scoutfs_incompat.go
- cmd/versitygw/gateway_test.go
- go.mod
- go.sum
- tests/integration/group-tests.go
- tests/integration/s3conf.go
- tests/integration/tests.go
- tests/integration/utils.go
This fixes the cases for racing uploads with the same object names. Before we were making some bad assumptions about what would cause an error when trying to link/rename the final object name into the namespace, but missed the case that another upload for the same name could be racing with this upload and causing an incorrect error.
This also changes the order of setting metadata to prevent accidental setting of metadata for the current upload to another racing upload.
Fixes #854
> fix: unexpected errors during upload races

- cmd/versitygw/admin.go
The admin client option for region was using the global region option. This was confusing for users since the access/secret are specified after the admin subcommand.
Fixes #880
> fix: add admin region cli option

- backend/posix/posix.go
- cmd/versitygw/test.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
The implementation handles put/get/delete operations for null versionId objects. If versionId attribute isn't set for an object, it's treated as `null`. 
It ensures that there is always exactly one object version with null versionId in a bucket at any given time.
The file name for the object with a null versionId is `null` in the versioning directory.
The listing of object versions follows this strategy:
1. Locate the object with the null versionId first.
2. Begin listing the other object versions.
3. Insert the null versionId object into its correct position in the list by comparing modification dates to maintain the proper order.
Fixes #864
> null versionId objects

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
If bucket versioning is enabled and the null versionId object is stored in posix directory, `GetObject` with versionId set to `null` returns `InvalidArgument`.
Resolves the issue of retrieving the null versionId object from posix directory by specifying versionId as `null`.
Fixes #894
> fix: Resolves the null object version get issue from posix directory

- backend/mkdir.go
- backend/posix/posix.go
- backend/posix/with_otmpfile.go
- backend/posix/without_otmpfile.go
- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
- cmd/versitygw/gateway_test.go
- cmd/versitygw/posix.go
- cmd/versitygw/scoutfs.go
We had 0755 hard coded for newly created directories before. This adds a user option to configure what the default mode permissions should be for newly created directories.
Fixes #878
> feat: add option to configure mode permissions on new directories

- backend/azure/azure.go
The latest azurite made a change where the blob metadata must be explicitly requested when calling NewListBlobsFlatPager(). We were taking action on metadata iteams, and the tests were failing due to these always missing without requesting metadata to be included in the response.
Fix is to enable metadata for the response.
> fix: azure list multipart uploads test failures

- backend/azure/azure.go
- backend/backend.go
- backend/common.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/walk_test.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3err/s3err.go
- s3response/s3response.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Closes #911
Implements pagination for the ListBuckets action both in posix and azure backends.
Removes double sorting by bucket name in posix, as os.ReadDir already gives sorted result.
> Listbuckets pagination

- backend/posix/posix.go
part of https://github.com/versity/versitygw/issues/919 (but we still need to solve https://github.com/valyala/fasthttp/issues/1889)
> make zero-copy GetObject possible via sendfile

- backend/walk.go
This fixes the biggest performance issue with ListObjects for me - it would recurse into all subdirectories, even when using a delimiter.
There are still a few issues:
- Large directories take forever to list.
- Parent directories are still walked for no reason - perhaps the posix backend should scope the os.DirFS() to the last directory in the prefix rather than starting at the root, and stitch the paths back together in `p.fileToObj`. I looked at doing that but wasn't sure if I'd hit a `prefix = ""` edge case.
Also fixes #903
> ListObjects: don't recurse beyond prefix

- backend/walk.go
similar to https://github.com/versity/versitygw/pull/904, avoid walking parent directories that are above the prefix
> ListObjects: don't walk parent directories

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- tests/integration/group-tests.go
- tests/integration/tests.go
The fileystem will return ENOTDIR if we try to access a file path where a parent directory within the path already exists as a file. In this case we need to return a standard 404 no such key since the request object does not exist within the filesytem.
Fixes #942
> fix: internal server error when object parent dir is a file

- backend/walk.go
- tests/integration/group-tests.go
- tests/integration/tests.go
We need to treat a prefix that has a parent component as a file instead of a directory in the filesystem as a non existing prefix instead of an internal server error. This error was caused because we were not handling ENOTDIR within the fs walk.
Fixes #949
> fix: listobjects internal server error for prefix not directory

- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
We need to check to make sure list-buckets returns a correct empty list when no buckets created.
> feat: add list-buckets test for no buckets

- auth/acl.go
- auth/iam_single.go
- s3err/s3err.go
In single `IAM` user mode, all IAM methods return a 'not supported' error. 
This update introduces an admin-specific error for this scenario.
> fix: Return XAdminMethodNotSupported error for single IAM methods.

- backend/meta/sidecar.go
- backend/posix/posix.go
- cmd/versitygw/posix.go
This adds the option to store metadata for objects and buckets within a hidden folder alongside the bucket or object:
bucket: .vgw_meta.<bucket>
object: .vgw_meta.<object>
Example invocation:
./versitygw -a myaccess -s mysecret posix --sidecar /tmp/gw
The attributes are stored by name within the hidden directory.
> feat: add optional sidecar files for metadata

- backend/meta/none.go
- backend/meta/sidecar.go
- cmd/versitygw/posix.go
This adds a NoMeta MetadataStorer that might be useful for read only filesystems that are populated with data not from the gateway. The limitation is that no incoming metadata is stored with the buckets or objects, and all buckets and objects will only have default metadata.
> feat: nometa option to disable bucket/object metadata

- .github/workflows/docker-bats.yml
There was a breaking change in latest awscli. This will tie the tests to the known working version until we can get a more permanenet fix for aws cli in place.
> chore: tie functional tests to aws cli version linux-x86_64-2.22.35

- s3api/middlewares/chunk.go
- s3api/utils/auth-reader.go
- s3api/utils/chunk-reader.go
- s3api/utils/signed-chunk-reader.go
- s3api/utils/unsigned-chunk-reader.go
Fixes #1034 
Implements an unsigned chunk reader with trailers to handle unsigned chunk encoding efficiently.  
The reader is optimized to function correctly with any buffer size provided to the `io.Reader`.  
It also parses and validates the checksum sent at the end of the stream.  
All checksum types are supported:  
1. `crc32`  
2. `crc32c`  
3. `crc64nvme`  
4. `sha1`  
5. `sha256`
> Unsigned streaming payload reader with trailers

- auth/iam_ipa.go
Potential fix for [https://github.com/versity/versitygw/security/code-scanning/15](https://github.com/versity/versitygw/security/code-scanning/15)
To fix the problem, we should avoid manually constructing the JSON string with `fmt.Sprintf` and instead use a structured approach to build the JSON object. This ensures that all necessary escaping is handled correctly by the JSON library.
- Replace the manual construction of the JSON string with a map and marshal it to JSON.
- This change will be made in the `newRequest` function in the `auth/iam_ipa.go` file.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 15: Potentially unsafe quoting

- cmd/versitygw/test.go
- runtests.sh
- tests/integration/s3conf.go
- tests/integration/tests.go
- tests/integration/utils.go
Adds the `--allow-insecure` flag to the test command to run integration tests in insecure mode by skipping TLS certificate verification for the HTTP client.  
Adds two steps in the SDK tests pipeline to run the SDK tests against the HTTPS gateway in both versioning-enabled and versioning-disabled modes.  
Upgrades all Go dependencies to the latest version.
> Integration tests over https

- s3api/utils/signed-chunk-reader.go
We were getting errors such as:
2025/02/07 19:24:28 Internal Error, write object data: write exceeds content length 87
whenever the chunk encoding did not have the correct chunk signatures. The issue was that the chunk encoding reader was reading from the underlying reader and then passing the full buffer read back to the caller if the underlying reader returned an error. This meant that we were not processing the chunk headers within the buffer due to the higher level error, and would possibly hand back the longer unprocessed chunk encoded stream to the caller that was in turn trying to write to the object file exceeding the content length limit.
Fixes #1056
> fix: chunk encoding with incorrect chunk signature

- auth/acl.go
- s3api/controllers/base.go
- s3api/middlewares/acl-parser.go
- s3api/middlewares/authentication.go
- s3api/middlewares/presign-auth.go
We were trying to parse a non existing acl and returning an internal server error due to invalid json acl data.
If the bucket acl does not exist, return a default acl with the root account as the owner.
This fixes #1060, but does not address the invalid acl format from s3cmd reported in #963.
> fix: return default bucket acl if none exists

- s3api/controllers/base.go
- tests/integration/tests.go
Fixes #1065 
Changes the returned error type for `UploadPart` to `ErrInvalidPartNumber`, if `partNumber` is not in `1-10000` range.
> UploadPart partnumber range validation

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/md5.go
- s3api/utils/auth-reader.go
- s3api/utils/csum-reader.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- s3err/s3err.go
- s3response/s3response.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #928 
Implements object integrity checksums in `POSIX`.  
The following checksum algorithms are supported (similar to AWS):  
1. **CRC32**  
2. **CRC32C**  
3. **SHA1**  
4. **SHA256**  
5. **CRC64NVME**
The checksums are Base64-encoded.  
- Checksums are calculated during object uploads (`PutObject`, `UploadPart`).  
- A checksum reader is layered on top of the existing readers.  
- When an object is copied (`CopyObject`), the checksum is recalculated if a different checksum type is specified.  
**Constraints:**  
- Multiple checksum types are not allowed for a single object.  
- It is not permitted to upload an object (`PutObject`) or its parts with differing checksum types.  
Checksum data is stored as extended attributes (`xattr`) in JSON format, including the checksum algorithm …
> Implements object integrity checksums

- backend/azure/azure.go
- backend/posix/posix.go
- s3api/controllers/base.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1061
`x-amz-mp-object-size` request header indicates the expected total object size of the multipart upload request. If there’s a mismatch between the specified object size value and the actual object size value, it results in an` HTTP 400 InvalidRequest` error.
Adds this header support in `posix` and `azure` backends.
> x-amz-mp-object-size header for CompleteMultipartUpload

- backend/posix/posix.go
- s3api/controllers/base.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Removes the `maxParts` and `maxUploads` nil checks, as its validation and value defaulting is put on front-end. If it's not provided it defaults to `1000`.
Adds request context cancelation/timeout check in parts loop, as it could take long to read and parse the directories.
Prealocates the `parts` slice length, based on the read directores length.
Adds integration tests for `ListObjects(V2)`, `ListParts`, `ListMultipartUploads` to check the defulat value to be 1000 for max*, if the provided value is greater than that.
> ListParts refactoring

- s3api/controllers/base.go
- s3api/utils/utils.go
The StreamResponseBody() called ctx.Write() in a loop with a small buffer in an attempt to stream data back to client. But the ctx.Write() was just calling append buffer to the response instead of streaming the data back to the client.
The correct way to stream the response back is to use (ctx *fasthttp.RequestCtx).SetBodyStream() to set the body stream reader, and the response will automatically get streamed back using the reader. This will also call Close() on our body since we are providing an io.ReadCloser.
Testing this should be done with single large get requests such as aws s3api get-object --bucket bucket --key file /tmp/data for very large objects. The testing shows significantly reduced memory usage for large objects once the streaming is enabled.
Fixes #1082
> fix: utils StreamResponseBody() memory use for large get requests

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- tests/integration/utils.go
Fixes #1018 
Adds quotes when storing object Etags.
> fix: Adds quotes for object Etags

- backend/posix/posix.go
- extract method to find top-level dirs, optionally including links to dirs
- rework ListBuckets and ListBucketsAndOwners to use FileInfo rather than DirEntry
Fixes #1081
> fix: admin list-buckets with bucketlinks option enabled

- auth/bucket_policy.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1092 
In multi-statement bucket policies, explicit `Deny` rules should take precedence over `Allow` rules.
This change updates the implementation to iterate through all policy statements. If a `Deny` statement is found, it immediately returns `AccessDenied`. If no `Deny` statement is found but an `Allow` statement is present, access is granted.
> fix: Prioritize explicit deny in bucket policy statements

- backend/s3proxy/s3.go
For any uninitialized input values, the s3 sdk expects these to be set to nil instead of the type zero value. Setting to the zero value is incorrectly making the server request think we are trying to set those parameters.
This sets all input parameters to nil for the default values. Many of these are already nil from the frontend, but this should protect against a future addition of input params for an api requests and not remembering to add teh zero value check on in the s3 backend.
We were previously getting the following error for put-object: <Error><Code>InvalidArgument</Code><Message>x-amz-object-lock-retain-until-date and x-amz-object-lock-mode must both be supplied</Message><Resource></Resource><RequestId></RequestId><HostId></HostId></Error>
> fix: s3 backend requires nil values for input params

- backend/s3proxy/s3.go
The frontend for versitygw wants to manage its own object retention, and these settings are conflicting with trying to forward object lock requests to the backend s3 server.
This disables object lock for the s3 backend for now until we can properly implement this for the backend. We will likely just need to add metadata to backend buckets and objects for out object retention settings.
> fix: s3 backend incorrect object lock settings

- backend/s3proxy/s3.go
We currently store bucket ACLs as tags in the backend S3 service. Some backend services do not implment tags though. In this case, we need to return the default bucket ACL for some continued functionality.
There is still more work to return more correct errors for setting ACLs when this is not implemented.
> fix: s3 proxy return default bucket acl when tags not implemented

- backend/meta/xattr.go
- backend/posix/posix.go
- backend/posix/with_otmpfile.go
- backend/posix/without_otmpfile.go
Instead of an internal server error, we should be returning method not allowed when trying to upload to a read only filesystem or make other modifications that are expected to fail. This will give clearer feedback to the clients that this is not expected to work.
Fixes #1062
> feat: return method not allowed when uploading to read only fs

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1004 
Fixes #1122 
Fixes #1120 
Separates `GetObject` and `UploadPartCopy` range parsing/validation. 
`GetObject` returns a successful response if acceptRange is invalid. 
Adjusts the range upper limit, if it exceeds the actual objects size for `GetObject`.
Corrects the `ContentRange` in the `GetObject` response.
Fixes the `UploadPartCopy` action copy source range parsing/validation.
`UploadPartCopy` returns `InvalidArgument` if the copy source range is not valid.
> fix: Fixes GetObject and UploadPartCopy actions data range parsing.

- backend/scoutfs/scoutfs.go
This was previously not including the bucket directory for the mutlipart temp file cleanup. This fixes leftovers in the tmp directories after uploading multipart uploads.
> fix: scoutfs multipart cleanup in complete/abort mp

- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
- cmd/versitygw/scoutfs.go
The part files for multipart uploads are considered temporary files and should not be archived by default. This adds the noarchive attribute to the part files to prevent scoutam from trying to archive these.
There is a new parameter, disablenoarchive, that will prevent adding the noarchive attribute to these files for the case where there is a desire to archive these temp files.
> feat: add noarchive to scoutfs part files

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3response/s3response.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1128
Adds `Content-Disposition`, `Content-Language`, `Cache-Control` and `Expires` object meta properties support in posix and azure backends. Changes the `PutObject` and `CreateMultipartUpload` actions backend input type to custom `s3response` types to be able to store `Expires` as any string.
> feat: Adds the Content-Disposition, Content-Language, Cache-Control and Expires object meta properties support in the gateway.

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- backend/walk.go
This syncs recent updates to posix for scoutfs backend including
the extra metadata such as Content-Disposition,
Content-Language, Cache-Control and Expires. This also fixes the
directory object listings that have a double trailing slash due
to the change in the backend.Walk().
This also simplifies head-object to call the posix on and then
post process for glacier changes. This allows keeping in closer
sync with posix head-object over time.
> feat: sync recent posix changes to scoutfs

- auth/iam_ldap.go
We were dropping the actual error before when doing the type conversion for the uid/gid
> fix: add err to ldap user/group conversion errors

- s3api/utils/chunk-reader.go
- s3api/utils/signed-chunk-reader.go
- s3err/s3err.go
Closes #1159
Fixes #1161
Implements signed chunk encoding with trailers in the gateway. The signed encoding (both with and without trailers) is now handled by the `ChunkReader`. Fixes the `ChunkReader` implementation to validate encoding headers byte by byte.
The chunk encoding with trailers follows the general signed chunk encoding pattern, but the final chunk includes the trailing signature (`x-amz-trailing-signature`) and the checksum header (`x-amz-checksum-x`, where `x` can be `crc32`, `crc32c`, `sha1`, `sha256`, or `crc64nvme`).
Adds validation for the `X-Amz-Trailer` header.
> feat: Implements signed chunk encoding with trailer in the gateway.

- auth/bucket_policy_actions.go
- backend/backend.go
- metrics/actions.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/middlewares/acl-parser.go
Implements the bucket cors s3 actions in FE to return `NotImplemented` error. Actions implemented:
- `PutBucketCors`
- `GetBucketCors`
- `DeleteBucketCors`
`Note`: no logic is implemented for the actions in any backend and no input or output data validation is added.
> feat: Implements bucket cors actions in FE to return not implemented.

- s3api/utils/utils.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1000
`GetObjectAttributes` returned `InvalidRequest` instead of `InvalidArgument` with description `Invalid attribute name specified.`. Fixes the logic in `ParseObjectAttributes` to ignore empty values for `X-Amz-Object-Attributes` headers to return `InvalidArgument` if all the specified object attributes are invalid.
> fix: Fixes the case for GetObjectAttributes to return InvalidArgument if a single invalid object attribute is provided.

- s3api/utils/signed-chunk-reader.go
- s3err/s3err.go
- tests/util/util_object.sh
Fixes #1165
The signed chunk encoding with trailers should return api error for:
1. Invalid checksum - `(InvalidRequest) Value for x-amz-checksum-x trailing header is invalid.`
2. Incorrect checksum - `(BadDigest) The x you specified did not match the calculated checksum.`
Where `x` could be crc32, crc32c, sha1 ...
> fix: Fixes the signed chunk trailer encoding to return proper api errors for invalid and incorrect checksums.

- backend/azure/azure.go
- backend/posix/posix.go
- s3api/controllers/base.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Closes #819
`ListObjects` returns object owner data in each object entity in the result, while `ListObjectsV2` has `fetch-owner` query param, which indicates if the objects owner data should be fetched. Adds these changes in the gateway to add `Owner` data in `ListObjects` and `ListObjectsV2` result. In aws the objects can be owned by different users in the same bucket. In the gateway all the objects are owned by the bucket owner.
> feat: Adds Owner data in ListObjects(V2) result

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1181
`DeleteObjects` should remove non-empty directory objects, which has been uploaded as a separate object. e.g
Upload -> `foo/bar`
Upload -> `foo/`
Delete -> `foo/`
The last action call should succeed.
The PR introduces changes which removes `ETag` from the directory object attempting to `delete`, which has been uploaded as a separate object.
> fix: Fixes non empty directory objects deletion

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1182
S3 calculates the `CRC64NVME` checksum of an object on object upload(`PutObject`), when no checksum algorithm or precalculated checksum header is provided. 
Makes the `CRC64NVME` checksum as default for `PutObject`, when no checksum is provided.
> fix: Makes the crc64nvme checksum as default for PutObject, even if no checksum is provided

- s3api/middlewares/authentication.go
- s3api/utils/auth-reader.go
- tests/integration/tests.go
Fixes #1171
As signature v2 is depracated the gateway doesn't support it. AWS S3 supports signature version 2 in some regions. For some regions the request fails with error:
```
InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```
The PR makes this change to return unsupported authorization mechanism for `sigV2` requests.
> fix: Returns ErrSignatureVersionNotSupported for sigV2 signed requests.

- tests/integration/tests.go
Increases the context cancelation deadline to `30` seconds to avoid timeouts in relatively large tests.
> fix: Increases the context cancelation deadline in integration tests.

- auth/object_lock.go
- s3response/s3response.go
Fixes #1193
Changes the xml root tag element to `LegalHold` in `GetObjectLegalHold` response.
> fix: Changes the GetObjectLegalHold result root tag to LegalHold

- auth/object_lock.go
- s3api/controllers/base.go
- tests/integration/tests.go
Fixes #1185
Fixes #1191
`PutObjectLegalHold` and `PutObjectRetention` should return `MalformedXML` if the request body is empty or invalid.`
> fix: Changes the error type to MalformedXML for PutObjectRetention and PutObjectLegalHold empty or invalid body

- s3api/controllers/base.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1204
Fixes #1205
Tag count in `PutBucketTagging` and `PutObjectTagging` is limited. `PutBucketTagging`: 50
`PutObjectTagging`: 10
Adds the changes to return errors respectively
> fix: Sets limit to tag set count to 10 for PutObjectTagging and 50 for PutBucketTagging

- s3err/s3err.go
For invalid bucket/object tags the error `Code` should be `InvalidTag` and `Message` - `The TagValue you have provided is invalid`.
> fix: Fixes the InvalidTag error Code and Description

- backend/common.go
- backend/posix/posix.go
- backend/posix/with_otmpfile.go
- backend/posix/without_otmpfile.go
- cmd/versitygw/main.go
- cmd/versitygw/posix.go
- extra/example.conf
O_TMPFILE can fail if the location we need to link the final file is not within the same filesystem. This can happen if there are different filesystem mounts within a bucket or if using zfs nested datasets within a bucket.
Fixes #1194
Fixes #1035
> feat: add option to disable use of O_TMPFILE

- .github/workflows/go.yml
We support several build targets, so need to verify these for PR checks. This adds the following build tsargets to the matrix builds:
os: [darwin, freebsd, linux]
arch: [amd64, arm64]
> feat: add matrix build tests to github workflow

- backend/s3proxy/s3.go
- cmd/versitygw/s3.go
Closes #1111 
Bucket ACLs and policies are now stored in the meta bucket as objects with the following prefixes:
- `vgw-meta-acl-<bucket-name>`
- `vgw-meta-policy-<bucket-name>`
The name of the meta bucket is provided during S3 proxy initialization. The gateway verifies whether the specified bucket exists; if it does not, an error is returned.
If no meta bucket is provided, the S3 proxy returns default values for ACL and policy actions.
> feat: Implements the logic to store buckets acl/policy in meta bucket as objects in s3 proxy

- backend/azure/azure.go
- backend/azure/err.go
- backend/common.go
- s3api/controllers/base.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1214
Fixes #1231
Fixes #1232
Implements `utils.ParseTagging` which is a generic implementation of parsing tags for both `PutObjectTagging` and `PutBucketTagging`.
- The actions now return `MalformedXML` if the provided request body is invalid.
- Adds validation to return `InvalidTag` if duplicate keys are present in tagging.
- For invalid tag keys, it creates a new error: `ErrInvalidTagKey`.
> fix: handles tag parsing error cases for PutBucketTagging and PutObjectTagging

- cmd/versitygw/main.go
- cmd/versitygw/plugin.go
- plugins/plugins.go
Introduce support for loading storage backends via go plugins.
Plugins can be created as shared libraries using go's plugin system (to be compiled using the command `go build -buildmode=plugin`). The new command `versitygw plugin <path_plugin>` can be used to run a backend defined in the plugin.
The shared library should export an instance of the interface `PluginBackend` in a variable named `Backend`.
Closes #1207
> Add support for plugin backends

- backend/azure/azure.go
- backend/common.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1215
Fixes #1216
`PutObject`, `CopyObject` and `CreateMultipartUpload` accept tag string as an http request header which should be url-encoded. The tag string should be a valid url-encoded string and each key/value pair should be valid, otherwise they should fail with `APIError`.
If the provided tag set contains duplicate `keys` the calls should fail with the same `InvalidURLEncodedTagging` error.
Not all url-encoded characters are supported by `S3`. The tagging string should contain only `letters`, `digits` and the following special chars:
- `-`
- `.`
- `/`
- `_`
- `+`
- ` `(space)
And their url-encoded versions: e.g. `%2F`(/), `%2E`(.) ... .
If the provided tagging string contains invalid `key`/`value`, the calls should fail with the following errors respectively: `invalid key` - …
> fix: fixes tagging string parsing for PutObject, CopyObject and CreateMultipartUpload

- s3api/middlewares/authentication.go
- s3api/middlewares/presign-auth.go
- s3api/utils/chunk-reader.go
- s3err/s3err.go
Fixes #961
Fixes #1248
The gateway should return a `MissingContentLength` error if the `Content-Length` HTTP header is missing for upload operations (`PutObject`, `UploadPart`).
The second fix involves enforcing a maximum object size limit of `5 * 1024 * 1024 * 1024` bytes (5 GB) by validating the value of the `Content-Length` header. If the value exceeds this limit, the gateway should return an `EntityTooLarge` error.
`Note`: Integration tests are skipped, as they get stuck in github pipelines.
> fix: Adds validation for Content-Length in upload operations.

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/scoutfs/scoutfs.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3response/s3response.go
The xml encoding for the s3.CompleteMultipartUploadOutput response type was not producing exactly the right field names for the expected complete multipart upload result.
This change follows the pattern we have had to do for other xml responses to create our own type that will encode better to the expected response.
This will change the backend.Backend interface, so plugins and other backends will have to make the corresponding changes.
> fix: xml response field names for complete multipart upload

- backend/scoutfs/scoutfs.go
The Etag can be quoted or not, so the check to verify the part Etag must remove the quotes before checking for equality. This check is the same now as posix.
> fix: scoutfs etag check for multipart uploads

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- s3api/controllers/base.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #1258
Fixes #1257
Closes #1244
Adds range queries support for `HeadObject`.
Fixes the range parsing logic for `GetObject`, which is used for `HeadObject` as well. Both actions follow the same rules for range parsing.
Fixes the error message returned by `GetObject`.
> fix: fixes the range parsing for GetObject. Adds range query support for HeadObject.

- backend/s3proxy/client.go
- backend/s3proxy/s3.go
- cmd/versitygw/s3.go
I want to proxy to a s3 service that does not support the domain bucket names, therefore exposing the `usePathStyle` options as parameter / env variable
> use path style

- s3event/event.go
- s3log/file.go
- s3log/webhook.go
Sending the following malformed request with eevnt notifcations or access logs enabled will cause a panic related to parsing the bucket and object from the invalid request path:
printf "GET GET  HTTP/1.1\r\nHost: $HOST\r\n\r\n" | nc 127.0.0.1 7070
The fix is to add bounds checks on the slice returned from splitting the request path to set the bucket/object.
Fixes #1269
> fix: panic with malformed request in event/log handlers

- s3api/debuglogger/logger.go
- s3api/middlewares/authentication.go
- s3api/utils/chunk-reader.go
- s3api/utils/signed-chunk-reader.go
- s3api/utils/unsigned-chunk-reader.go
Closes #1221
Adds debug logging for `signed`/`unsigned` chunk readers. Adds the `debuglogger.Infof` log method, which prints out green info logs with `[INFO]:` prefix. The debug logging inclues some chunk details: size, signature, trailers. It also prints out stash/release stash operations. The error cases are logged with standart yellow `[DEBUG]:` prefix. The `String to sign` block in signed chunk reader is logged in purple horizontal borders with title.
**Example Screenshots**
> feat: adds debug logging for chunk readers.

- tests/integration/tests.go
Fixes #1271
In the `Versioning_GetObject_success` integration test the contexts are canceled before reading the full request body after `GetObject`. 
Changes the behaviour to defer the context cancelation, to be sure it's canceled after the full request body is read.
> fix: fixes the context cancelation issue in Versioning_GetObject_success integration test.

- backend/common.go
- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
Fixes #1277
Fixes #1235
Adds surrounding quotes on `ETag` when creating a directory object. Adds the quotes in `UploadPartCopy` as well.
> fix: adds the surrounding quotes on ETag in PutObject for dir objects and in UploadPartCopy.

- s3response/s3response.go
mount-s3 has strict XML parsing which doesn't like receiving this tag empty. An empty ContinuationToken causes mount-s3 to error out and stop processing requests.
> add omit on empty for ContinuationToken

- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/backend_moq_test.go
- s3api/controllers/base_test.go
- s3response/s3response.go
Fixes #1276
Creates the custom `s3response.CopyObjectOutput` type to handle the `LastModified` date property formatting correctly. It uses `time.RFC3339` to format the date to match the format that s3 uses.
> fix: fixes the LastModified date formatting in CopyObject result.

- .github/workflows/system.yml
- backend/posix/posix.go
- backend/s3proxy/s3.go
- backend/walk.go
- s3response/s3response.go
Fixes the response body parsing for all available actions to correctly parse date fields (e.g., `LastModified`) into the correct format.
> fix: fixes all the available actions date xml marshalling for response body.

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1288
If the checksum algorithm/type is not specified during multipart upload initialization, it is considered `null`, and the `ListParts` result should also set it to `null`.
> fix: overrides empty checksum type and algorithm with 'null' for ListParts

- tests/integration/tests.go
`context` gets cancelled early before reading the full body in the `GetObject_with_range` integration test. This change defers the context cancelation to make sure the full body is ready and the context isn't canceled in the middle of the request body read.
> fix: fixes the early context cancelation issue in GetObject_with_range integration test.

- auth/iam.go
- auth/iam_ipa.go
- auth/iam_ldap.go
- cmd/versitygw/admin.go
- s3api/controllers/admin.go
- s3api/router.go
Closes #1295
Makes the user `role` mutable in /update-user admin endpoint. Integrates the changes in the `admin update-user` cli command, by adding the `role` flag for a user role modification.
> feat: makes the user role editable in /update-user iam endpoint

- backend/azure/azure.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
There were a couple of cases that would return an error for the non existing bucket acl instead of treating that as the default acl.
This also cleans up the backends that were doing their own acl parsing instead of using the auth.ParseACL() function.
Fixes #1304
> fix: non existing bucket acl parsing

- .github/workflows/host-style-tests.yml
- Makefile
- tests/host-style-tests/Dockerfile
- tests/host-style-tests/dnsmasq.conf
- tests/host-style-tests/docker-compose.yml
Adds a GitHub Actions workflow to run the `host-style` tests inside Docker containers. The tests are executed in a Docker environment using `Docker Compose` with three containers: one for running the tests, one for setting up the server, and one using the `dnsmasq` image for `DNS` server configuration.
> feat: automates the host-style tests in the pipeline

- .github/SECURITY.md
Adds a `SECURITY.md` file under the `.github` directory, following [GitHub's guidelines](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository). This document instructs users on how to report security vulnerabilities, recommending the use of GitHub Security Advisories—a private and secure method for handling security issues in open source projects.
The file will appear in the [Security Policy section](https://github.com/versity/versitygw/security/policy) of the repository.
> feat: add SECURITY.md to define GitHub security policy

- s3api/utils/name_validate.go
- s3api/utils/path.go
- s3api/utils/path_test.go
This adds an object name validation util to check if the object
path would resolve to a path outside of the bucket directory.
S3 returns Bad Request for these type of paths:
% aws s3api put-object --bucket mybucket --key test/../../hello
An error occurred (400) when calling the PutObject operation: Bad Request
> fix: add object path validation for posix paths

- auth/access-control.go
- auth/acl.go
- auth/bucket_policy.go
- auth/bucket_policy_actions.go
- auth/bucket_policy_principals.go
- auth/object_lock.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/acl-parser.go
- s3api/middlewares/admin.go
- s3api/middlewares/authentication.go
- s3api/middlewares/presign-auth.go
- s3api/middlewares/public-bucket.go
- s3api/middlewares/set-default-keys.go
- s3api/server.go
- s3api/utils/chunk-reader.go
- s3api/utils/context-keys.go
- s3api/utils/presign-auth-reader.go
- s3err/s3err.go
- s3event/event.go
- s3log/file.go
- s3log/file_admin.go
- s3log/webhook.go
- tests/integration/group-tests.go
- tests/integration/s3conf.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #1325 
This implementation introduces **public buckets**, which are accessible without signature-based authentication.
Public buckets support a set of actions on buckets and objects, returning various errors based on the S3 action type and permissions (ACL or policy). The implementation aligns with the table provided in [this gist](https://gist.github.com/niksis02/5919d52d6112537a31c14d9abfa89ac0).
There are two ways to grant public access to a bucket:
* **Bucket ACLs**
* **Bucket Policies**
The implementation includes an `AuthorizePublicBucketAccess` middleware, which checks if public access has been granted to the bucket. If so, authentication middlewares are skipped. For unauthenticated requests, appropriate errors are returned based on the specific S3 action.
---
**1. …
> feat: implements public bucket access.

- backend/posix/posix.go
- backend/scoutfs/scoutfs.go
- s3api/controllers/base.go
- s3api/controllers/base_test.go
- s3api/middlewares/bucket-object-name-validator.go
- s3api/server.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Implements a middleware that validates incoming bucket and object names before authentication. This helps prevent malicious attacks that attempt to access restricted or unreachable data in `POSIX`.
Adds test cases to cover such attack scenarios, including false negatives where encoded paths are used to try accessing resources outside the intended bucket.
Removes bucket validation from all other layers—including `controllers` and both `POSIX` and `ScoutFS` backends — by moving the logic entirely into the middleware layer.
> feat: adds a middleware to validate bucket/object names

- auth/acl.go
- backend/azure/azure.go
- backend/backend.go
- backend/posix/posix.go
- backend/s3proxy/s3.go
- s3api/controllers/admin.go
- s3api/controllers/admin_test.go
- s3api/controllers/backend_moq_test.go
We were incorrctly trying to pass through the admin request actions through to the backend s3 service in s3proxy. This was resulting in internal server errors since not all s3 backends would understand these requests. Instead the gateway needs to handle these requests directly.
Fixes #1381
> fix: admin bucket actions for s3proxy

- s3api/controllers/base.go
The debuglogger logs will only get printed if debug is enabled, but we always want the internal server error logs to be logged by the service since this is usually some actionable error that needs to be addressed with the backend storage system.
This changes internal server error logs to always to sent to stderr.
> fix: always log internal server error messages to stderr

- auth/access-control.go
- backend/common.go
- backend/posix/posix.go
- s3api/controllers/object-put.go
- s3api/controllers/object-put_test.go
- s3api/utils/utils.go
- s3api/utils/utils_test.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1388
Fixes #1389
Fixes #1390
Fixes #1401
Adds the `x-amz-copy-source` header validation for `CopyObject` and `UploadPartCopy` in front-end. The error:
```
ErrInvalidCopySource: {
Code:           "InvalidArgument",
Description:    "Copy Source must mention the source bucket and key: sourcebucket/sourcekey.",
HTTPStatusCode: http.StatusBadRequest,
},
```
is now deprecated.
The conditional read/write headers validation in `CopyObject` should come with #821 and #822.
> feat: adds copy source validation for x-amz-copy-source header.

- s3api/controllers/object-get.go
- s3api/controllers/object-head.go
- s3api/controllers/object-head_test.go
- tests/integration/group-tests.go
- tests/integration/s3conf.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #1385
When accessing a specific object version, the user must have the `s3:GetObjectVersion` permission in the bucket policy. The `s3:GetObject` permission alone is not sufficient for a regular user to query object versions using `HeadObject`.
This PR fixes the issue and adds integration tests for both `HeadObject` and `GetObject`. It also includes cleanup in the integration tests by refactoring the creation of user S3 clients, and moves some test user data to the package level to avoid repetition across tests.
> fix: fixes the HeadObject version access control with policies.

- s3err/s3err.go
Fixes #1387
The `Code` for `ErrInvalidBucketAclWithObjectOwnership` error should be `InvalidBucketAclWithObjectOwnership` instead of `ErrInvalidBucketAclWithObjectOwnership`. The PR fixes the typo in the error code.
> fix: fixes the InvalidBucketAclWithObjectOwnership error code.

- s3api/controllers/base.go
- s3api/controllers/bucket-list.go
- s3api/controllers/bucket-list_test.go
- s3response/s3response.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #1374
Hardcodes the gateway region for each bucket entry in `ListBuckets` result as bucket region.
> fix: adds bucket region in ListBuckets result

- s3api/middlewares/body-reader.go
Fixes #1418
If neither the `Transfer-Encoding` nor the `Content-Length` headers are provided in chunked uploads, **fasthttp** assumes there is no request body and sets the request body reader to `nil`. This leads to a panic in the auth reader when it attempts to read the body.
The fix ensures that if the request body reader is `nil`, it is overridden with an `empty reader` to prevent panics.
> fix: fixes the nil body reader panic.

- backend/posix/posix.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1342
This PR includes two main changes:
1. It fixes the case where `x-amz-checksum-x` (precalculated checksum headers) are not provided for `UploadPart`, and the checksum type for the multipart upload is `FULL_OBJECT`. In this scenario, the server no longer returns an error.
2. When no `x-amz-checksum-x` is provided for `UploadPart`, and `x-amz-sdk-checksum-algorithm` is also missing, the gateway now calculates the part checksum based on the multipart upload's checksum algorithm and stores it accordingly.
Additionally, the PR adds integration tests for:
* The two cases above
* The case where only `x-amz-sdk-checksum-algorithm` is provided
> fix: fixes the UploadPart failure with no precalculated checksum header for FULL_OBJECT checksum type

- cmd/versitygw/main.go
- extra/example.conf
- go.mod
- go.sum
- s3event/event.go
- s3event/rabbitmq.go
This adds support for rabbitmq publisher for s3 events. The mechanics are similar to kafka and nats, but will use the amqp protocol to send bucket events.
> feat: add rabbitmq s3 event notification support

- s3log/file.go
This fixes a nil deref when the region is not set for the access log. This was reported to happen during netwrok security scans likely sending unexpected requests triggering this case.
Fixes #1463
> fix: panic in access log when region header not set in request context

- auth/bucket_policy_actions.go
- metrics/actions.go
- s3api/router.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1444
Adds `NotImplemented` routes for bucket logging S3 actions:
- `PutBucketLogging`
- `GetBucketLogging`
> feat: adds not implemented routes for bucket logging actions

- auth/bucket_policy_actions.go
- metrics/actions.go
- s3api/router.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1455
Adds `NotImplemented` routes for bucket request payment S3 actions:
- `PutBucketRequestPayment`
- `GetBucketRequestPayment`
> feat: adds not implemented routes for bucket request payment actions

- auth/bucket_policy_actions.go
- metrics/actions.go
- s3api/router.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1453
Adds `NotImplemented` routes for bucket notification configuration S3 actions:
- `PutBucketNotificationConfiguration`
- `GetBucketNotificationConfiguration`
> feat: adds not implemented routes for bucket notification configuration actions

- auth/bucket_policy_actions.go
- metrics/actions.go
- s3api/router.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #1452
Adds `NotImplemented` routes for bucket accelerate configuration S3 actions:
- `PutBucketAccelerateConfiguration`
- `GetBucketAccelerateConfiguration`
> feat: adds not implemented routes for bucket accelerate configurationactions

- backend/azure/azure.go
- tests/integration/group-tests.go
- tests/integration/tests.go
This changes the marker/continuation token from the object name to the marker from the azure list objects pager. This is needed because passing the object name as the token to the azure next call causes the Azure API to throw 400 Bad Request with InvalidQueryParameterValue. So we have to use the azure marker for compatibility with the azure API pager.
Fixes #1457
> fix: update marker/continuation token to be the azure next marker

- auth/bucket_cors.go
- auth/bucket_cors_test.go
- s3api/controllers/options.go
- s3api/controllers/options_test.go
- s3api/middlewares/apply-bucket-cors.go
- tests/integration/tests.go
- tests/integration/utils.go
Fixes #1486
* Adds the `Access-Control-Allow-Headers` response header to CORS responses for both **OPTIONS preflight requests** and any request containing an `Origin` header.
* The `Access-Control-Allow-Headers` response includes only the headers specified in the `Access-Control-Request-Headers` request header, always returned in lowercase.
* Fixes an issue with allow headers comparison in cors evaluation by making it case-insensitive.
* Adds missing unit tests for the **OPTIONS controller**.
> fix: adds Acces-Control-Allow-Headers to cors responses

- backend/scoutfs/scoutfs.go
- backend/scoutfs/scoutfs_compat.go
- cmd/versitygw/scoutfs.go
- extra/example.conf
This adds the same versioning dir option that is found in the posix backend to scoutfs backend. Functionality is the same.
> feat: add versioning dir option to scoutfs backend

- auth/bucket_policy.go
- auth/bucket_policy_actions.go
- auth/bucket_policy_actions_test.go
- auth/bucket_policy_effect_test.go
- auth/bucket_policy_principals_test.go
- auth/bucket_policy_resources.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1488
Adds full wildcard (`*`) and single-character (`?`) support for bucket policy actions, fixes resource detection with wildcards, and includes unit tests for `bucket_policy_actions`, `bucket_policy_effect`, and `bucket_policy_principals`.
> fix: adds full wildcard and any character match for bucket policy actions

- auth/iam.go
- auth/iam_ldap.go
- cmd/versitygw/main.go
be able to debug IAM LDAP queries.
be consistent between GetUserAccount() and ListUserAccounts() on how to build the search filters.
objectClasses were missing in GetUserAccount research filter, leading to a bad result for example when a posixgGroup have the same name as a posixUser.
> correct a bug when using glauth as LDAP IAM

- auth/bucket_policy_actions.go
- metrics/actions.go
- s3api/controllers/base_test.go
- s3api/controllers/bucket-get.go
- s3api/controllers/bucket-get_test.go
- s3api/router.go
- s3response/s3response.go
- tests/integration/group-tests.go
- tests/integration/tests.go
GetBucketLocation is being deprecated by AWS, but is still used by some clients. We don't need any backend handlers for this since the region is managed by the frontend. All we need is to test for bucket existence, so we can use HeadBucket for this.
Fixes #1499
> feat: add get bucket location frontend handlers

- auth/access-control.go
- s3api/controllers/bucket-delete.go
- s3api/controllers/bucket-get.go
- s3api/controllers/bucket-head.go
- s3api/controllers/bucket-post.go
- s3api/controllers/bucket-put.go
- s3api/controllers/object-delete.go
- s3api/controllers/object-get.go
- s3api/controllers/object-head.go
- s3api/controllers/object-post.go
- s3api/controllers/object-put.go
- s3api/middlewares/public-bucket.go
- s3api/utils/utils.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
GetObject allows overriding response headers with the following paramters:
response-cache-control
response-content-disposition
response-content-encoding
response-content-language
response-content-type
response-expires
This is only valid for signed (and pre-singed) requests. An error is returned for anonymous requests if these are set.
More info on the GetObject overrides can be found in the GetObject API reference.
Fixes #1501
> feat: add response header overrides for GetObject

- s3api/controllers/bucket-get.go
There was a change to the auth.VerifyAccess that changed IsPublicBucket to IsPublicRequest, but another PR
(GetBucketLocation) that was merged at the same time (and not rebased) was using the old version.
Update this to fix the build.
> fix: previous pr was not rebased before merging and caused a build error

- backend/azure/azure.go
- backend/common.go
- backend/posix/posix.go
- s3api/controllers/object-get.go
- s3api/controllers/object-head.go
- s3api/utils/utils.go
- s3err/s3err.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Closes #882
Implements conditional reads for `GetObject` and `HeadObject` in the gateway for both POSIX and Azure backends. The behavior is controlled by the `If-Match`, `If-None-Match`, `If-Modified-Since`, and `If-Unmodified-Since` request headers, where the first two perform ETag comparisons and the latter two compare against the object’s `LastModified` date. No validation is performed for invalid ETags or malformed date formats, and precondition date headers are expected to follow RFC1123; otherwise, they are ignored.
The Integration tests cover all possible combinations of conditional headers, ensuring the feature is 100% AWS S3–compatible.
> feat: implements conditional reads for GetObject and HeadObject

- backend/posix/posix.go
The customMove (i.e. `scoutfs.MoveData`) won't affect the file position on the target file (unlike `io.Copy`)... so this fixes the problem of uploading files not aligned to 4096 blocks..
> Fix scoutfs backend s3 upload with non-aligned size.

- s3api/utils/signed-chunk-reader.go
The following panic was triggered when mc client (that uses chunked uploads) would upload a 171164 byte file. This likely could have been hit with other sizes as well, but this size was able to reliably reproduce the issue.
panic: runtime error: slice bounds out of range [:2] with capacity 1
goroutine 66 [running]:
github.com/versity/versitygw/s3api/utils.(*ChunkReader).parseChunkHeaderBytes(0x14000276200, {0x14000167fff?, 0x14000103180?, 0x200000003?})
versitygw/s3api/utils/signed-chunk-reader.go:372 +0xe54
github.com/versity/versitygw/s3api/utils.(*ChunkReader).parseAndRemoveChunkInfo(0x14000276200, {0x14000167fff, 0x1, 0x1})
versitygw/s3api/utils/signed-chunk-reader.go:251 +0x50
github.com/versity/versitygw/s3api/utils.(*ChunkReader).Read(0x14000276200, {0x14000160000, 0x14000056c00?, …
> fix: panic in signed-chunk-reader with incorrect debug string

- backend/walk.go
- backend/walk_test.go
- tests/integration/tests.go
- tests/integration/utils.go
The original Walk function used the native WalkDir and ReadDir which did not
guarantee lexicographic ordering of results for cases where including directory
slash changes the sort order. This caused incorrect paginated responses because
S3 APIs require strict lexicographic ordering where directories with trailing
slashes sort correctly relative to files. For example, dir1/a.b/ must come
before dir1/a/ in the results, but fs.WalkDir was returning them in filesystem
sort order which reversed the order due to not taking in account the trailing
"/".
This also lead to cases of continuous looping of paginated listobjects results
when the marker was set out of order from the expected results.
To address this fundamental ordering issue, the entire directory traversal
mechanism was replaced with a …
> fix: lex sort order of listobjects backend.Walk

- backend/walk.go
- backend/walk_test.go
- tests/integration/tests.go
- tests/integration/utils.go
Similar to:
8e18b43116d889a6053f75e6be93121d5c92ba70
fix: lex sort order of listobjects backend.Walk
But now the "Versions" walk.
The original backend.WalkVersions function used the native WalkDir and ReadDir which did not guarantee lexicographic ordering of results for cases where including directory slash changes the sort order. This caused incorrect paginated responses because S3 APIs require strict lexicographic ordering where directories with trailing slashes sort correctly relative to files. For example, dir1/a.b/ must come before dir1/a/ in the results, but fs.WalkDir was returning them in filesystem sort order which reversed the order due to not taking in account the trailing "/".
> fix: lex sort order of listobjectversions backend.WalkVersions

- s3api/middlewares/authentication.go
- s3api/middlewares/presign-auth.go
- s3api/middlewares/public-bucket.go
- s3api/utils/auth-reader.go
- s3api/utils/presign-auth-reader.go
- s3api/utils/presign-auth-reader_test.go
- s3err/presigned-urls.go
- s3err/s3err.go
- s3err/sigv4.go
- tests/integration/group-tests.go
- tests/integration/tests.go
Fixes #1540
Fixes #1538
Fixes #1513
Fixes #1425
Fixes SigV4 authentication and presigned URL error handling. Adds two sets of errors in the `s3err` package for these authentication mechanisms.
* Adds a check to return a custom "not supported" error when `X-Amz-Security-Token` is present in presigned URLs.
* Adds a check to return a custom "not supported" error when the `AWS4-ECDSA-P256-SHA256` algorithm is used in presigned URLs.
> fix: fixes sigv4 and presigned url auth errors.

- s3api/controllers/object-post.go
- s3api/controllers/object-post_test.go
- s3err/s3err.go
- tests/integration/tests.go
Fixes #1328
If `CompleteMultipartUpload` is attempted with empty `Parts` list, the gateway used to return `InvalidRequest`. Now it's changed to `MalformedXML`.
> fix: changes empty mp parts error on CompleteMultipartUpload

- s3api/middlewares/host-style-parser.go
For bucket operations a typical host-style request looks like `bucket.host/`. `HostStyleParser` parses the bucket from host header and appends in the path, by changing the requests to `path-styled`. For bucket operations the original request path is `bucket.host/`, after reconsturction it looks like `/bucket/`: a trailing `/` is added at the end.
The PR adds a check to not append this trailing `/` at the end for bucket operations, to keep consistency with path-style requests.
> fix: removes trailing / for bucket operations in host-style parser

- s3api/router.go
Fixes #1545
`Content-Md5` should be validated/calculated only for the actions containing request body, which are:
* All bucket `PUT` operations(PutBucketTagging, PutBucketVersioning ...)
* All object `PUT` operations(PutObject, UploadPart ...) except for object copy ones(CopyObject, UploadPartCopy)
* Object `POST` operations(CompleteMultipartUpload, RestoreObject ...), but not for `CreateMultipartUpload`, as it doesn't have request body.
* Bucket `POST` operation(DeleteObjects).
The PR removes the `Content-Md5` check from bucket/object GET/HEAD operations and from `PUT`/`POST` operations not expecting request body.
> fix: removes content-md5 check from the actions where it's unnecessary

- cmd/versitygw/main.go
- debuglogger/logger.go
- s3api/admin-server.go
- s3api/controllers/base.go
- s3api/server.go
- s3api/server_test.go
- s3api/utils/context-keys.go
Fiber includes a built-in panic recovery middleware that catches panics in route handlers and middlewares, preventing the server from crashing and allowing it to recover. Alongside this, a stack trace handler has been implemented to store system panics in the context locals (stack).
Both the S3 API server and the Admin server use a global error handler to catch unexpected exceptions and recovered panics. The middleware’s logic is to log the panic or internal error and return an S3-style internal server error response.
Additionally, dedicated **Panic** and **InternalError** loggers have been added to the `s3api` debug logger to record system panics and internal errors in the console.
> feat: implements fiber panic recovery

- .github/workflows/docker-bats.yml
- Dockerfile
- README.md
- cmd/versitygw/plugin.go
- docker-entrypoint.sh
- extra/example.conf
- extra/versitygw@.service
Using Docker ENTRYPOINT should allow for configuration of running versitygw within Docker container similar to how the systemd service is setup with environment variables.
This also adds the backends azure and plugin to the acceptable backend options for both docker and systemd.
Fixes #1335
> feat: use docker entrypoint for flexible env var docker config

- cmd/versitygw/test.go
- runtests.sh
- tests/integration/concurrency.go
- tests/integration/group-tests.go
- tests/integration/output.go
- tests/integration/tests.go
- tests/integration/utils.go
This change introduces concurrent execution for integration tests. It adds a mechanism to run tests either synchronously or in parallel, controlled by a new flag. By default, tests continue to run in synchronous mode to maintain predictable behavior during local development. In GitHub Actions, the tests are now executed in parallel mode to significantly reduce overall runtime.
The implementation uses a semaphore-based concurrency control to limit the number of parallel test executions and ensures graceful shutdown through context cancellation. This approach improves test performance while keeping the system stable and backward compatible.
> feat: concurrent execution of integration tests
